import json
import os
import subprocess
import sys

import pandas as pd
import streamlit as st


# ============================================================
# SMARTFLOW - MULTI-OBJECT TRACKING DASHBOARD
# ============================================================

st.set_page_config(
    page_title="SMARTFLOW",
    page_icon="🚦",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# PATHS
# ============================================================

COUNT_REPORT_FILE = "reports/count_report.csv"
INPUT_DIR = "input"
OUTPUT_DIR = "output"
REPORT_DIR = "reports"

def get_input_videos():
    """Find all MP4 input videos in the input folder."""
    if not os.path.isdir(INPUT_DIR):
        return []
    return sorted(
        [
            os.path.join(INPUT_DIR, name)
            for name in os.listdir(INPUT_DIR)
            if name.lower().endswith(".mp4")
        ]
    )

def video_stem(video_path):
    """Return the input video's filename without extension."""
    return os.path.splitext(os.path.basename(video_path))[0]

def video_output_path(video_path):
    """Return the H.264 output path preferred by the dashboard."""
    return os.path.join(
        OUTPUT_DIR,
        f"smartflow_{video_stem(video_path)}_tracked_h264.mp4",
    )

def video_raw_output_path(video_path):
    """Return the OpenCV output path."""
    return os.path.join(
        OUTPUT_DIR,
        f"smartflow_{video_stem(video_path)}_tracked.mp4",
    )

def video_data_path(video_path):
    """Return the per-video CSV generated by main.py."""
    return os.path.join(
        REPORT_DIR,
        f"{video_stem(video_path)}_traffic_data.csv",
    )


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown(
    """
    <style>
    .main-title {
        font-size: 42px;
        font-weight: 800;
        margin-bottom: 0;
    }

    .subtitle {
        font-size: 18px;
        margin-top: 0;
        margin-bottom: 25px;
    }

    .status-card {
        border: 1px solid rgba(128,128,128,0.30);
        border-radius: 12px;
        padding: 18px;
        text-align: center;
        min-height: 125px;
        margin-bottom: 10px;
    }

    .status-label {
        font-size: 14px;
        font-weight: 600;
        margin-bottom: 8px;
    }

    .status-value {
        font-size: 30px;
        font-weight: 800;
    }

    .status-description {
        font-size: 13px;
        margin-top: 6px;
    }

    .info-box {
        border-left: 4px solid #00a6a6;
        padding: 12px 16px;
        border-radius: 6px;
        margin: 10px 0;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def find_video():
    """Return a sensible default input video."""
    videos = get_input_videos()
    if not videos:
        return None

    traffic = os.path.join(INPUT_DIR, "traffic.mp4")
    if traffic in videos:
        return traffic

    return videos[0]


def load_csv(data_file):
    """Load SMARTFLOW traffic data for the selected video."""
    if not os.path.exists(data_file):
        return None

    try:
        df = pd.read_csv(data_file)

        if df.empty:
            return None

        return df

    except Exception as exc:
        st.error(f"Could not read {data_file}: {exc}")
        return None


def number_value(row, column, default=0):
    """Safely read a numeric CSV value."""
    try:
        value = row.get(column, default)

        if pd.isna(value):
            return default

        return float(value)

    except Exception:
        return default


def integer_value(row, column, default=0):
    """Safely read an integer CSV value."""
    return int(round(number_value(row, column, default)))


def parse_object_types(value):
    """Parse the JSON object_types column."""
    if value is None or pd.isna(value):
        return {}

    try:
        data = json.loads(str(value))

        if isinstance(data, dict):
            return {
                str(key): int(float(val))
                for key, val in data.items()
            }

    except Exception:
        pass

    return {}


def render_card(label, value, description=""):
    """Render a dashboard status card."""
    st.markdown(
        f"""
        <div class="status-card">
            <div class="status-label">{label}</div>
            <div class="status-value">{value}</div>
            <div class="status-description">{description}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="main-title">SMARTFLOW</div>',
    unsafe_allow_html=True,
)

st.markdown(
    '<div class="subtitle">'
    "Multi-Object Tracking & Counting From Video"
    "</div>",
    unsafe_allow_html=True,
)


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("SMARTFLOW")

st.sidebar.markdown(
    """
    ### System
    - YOLO11 Object Detection
    - ByteTrack Multi-Object Tracking
    - OpenCV Video Processing
    - Streamlit Dashboard
    """
)

st.sidebar.markdown("---")

st.sidebar.markdown(
    """
    ### Counting Method

    Each detected object receives a tracking ID.
    An object is counted when its tracked center
    crosses the virtual counting line.

    The same tracking ID is stored in a counted-ID
    set so it is not counted again during the run.
    """
)


# ============================================================
# VIDEO SELECTION & ANALYSIS
# ============================================================

st.subheader("Input Video")

input_videos = get_input_videos()

if not input_videos:
    st.error(
        "No MP4 videos found in the input folder. "
        "Add a video to SMARTFLOW\\input."
    )
    st.stop()

default_video = find_video()
default_index = (
    input_videos.index(default_video)
    if default_video in input_videos
    else 0
)

selected_input_video = st.selectbox(
    "Select a video to analyze",
    input_videos,
    index=default_index,
    format_func=lambda path: os.path.basename(path),
)

selected_stem = video_stem(selected_input_video)
selected_data_file = video_data_path(selected_input_video)
selected_raw_output = video_raw_output_path(selected_input_video)
selected_h264_output = video_output_path(selected_input_video)

col_run, col_info = st.columns([1, 3])

with col_run:
    run_analysis = st.button(
        "▶ Run Analysis",
        type="primary",
        width="stretch",
    )

with col_info:
    st.caption(
        f"Input: {selected_input_video}  |  "
        f"Output: {selected_h264_output}"
    )

if run_analysis:
    with st.spinner(
        f"Processing {os.path.basename(selected_input_video)} "
        "with YOLO11 + ByteTrack..."
    ):
        try:
            result = subprocess.run(
                [
                    sys.executable,
                    os.path.join("src", "main.py"),
                    selected_input_video,
                ],
                capture_output=True,
                text=True,
                cwd=os.getcwd(),
            )

            if result.returncode == 0:
                st.success(
                    f"Analysis completed successfully for "
                    f"{os.path.basename(selected_input_video)}."
                )

                # Convert OpenCV MP4 to browser-friendly H.264.
                try:
                    import imageio_ffmpeg

                    ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()

                    convert = subprocess.run(
                        [
                            ffmpeg,
                            "-y",
                            "-i",
                            selected_raw_output,
                            "-c:v",
                            "libx264",
                            "-pix_fmt",
                            "yuv420p",
                            "-movflags",
                            "+faststart",
                            selected_h264_output,
                        ],
                        capture_output=True,
                        text=True,
                        cwd=os.getcwd(),
                    )

                    if convert.returncode != 0:
                        st.warning(
                            "Analysis completed, but automatic H.264 "
                            "conversion failed. The raw MP4 output "
                            "is still available."
                        )
                except Exception as exc:
                    st.warning(
                        "Analysis completed, but H.264 conversion "
                        f"was unavailable: {exc}"
                    )

                if result.stdout:
                    with st.expander("Processing log"):
                        st.code(result.stdout)

                st.rerun()

            else:
                st.error("SMARTFLOW analysis failed.")
                if result.stdout:
                    st.code(result.stdout)
                if result.stderr:
                    st.code(result.stderr)

        except Exception as exc:
            st.error(f"Could not start SMARTFLOW: {exc}")


# ============================================================
# LOAD DATA
# ============================================================

df = load_csv(selected_data_file)

if df is None:
    st.warning(
        "No analysis data found for the selected video. "
        "Click **Run Analysis** to process it."
    )
    st.info(
        f"Expected file: {selected_data_file}"
    )
    st.stop()


# ============================================================
# LATEST DATA
# ============================================================

latest = df.iloc[-1]


objects_in_frame = integer_value(
    latest,
    "objects",
    integer_value(latest, "vehicles", 0),
)


total_counted = (
    integer_value(latest, "right_direction", 0)
    + integer_value(latest, "left_direction", 0)
)


left_count = integer_value(
    latest,
    "left_direction",
    0,
)


right_count = integer_value(
    latest,
    "right_direction",
    0,
)


density = str(
    latest.get("density", "UNKNOWN")
)


flow_rate = number_value(
    latest,
    "flow_rate",
    0,
)


# ============================================================
# OBJECT COMPOSITION
# ============================================================

persons = integer_value(
    latest,
    "persons",
    0,
)

bicycles = integer_value(
    latest,
    "bicycles",
    0,
)

cars = integer_value(
    latest,
    "cars",
    0,
)

motorcycles = integer_value(
    latest,
    "motorcycles",
    0,
)

buses = integer_value(
    latest,
    "buses",
    0,
)

trucks = integer_value(
    latest,
    "trucks",
    0,
)

other_objects = integer_value(
    latest,
    "other_objects",
    0,
)


# ============================================================
# MAIN METRICS
# ============================================================

st.subheader("Traffic / Object Overview")

metric_columns = st.columns(4)

with metric_columns[0]:
    render_card(
        "Objects in Frame",
        objects_in_frame,
        "Objects currently visible",
    )

with metric_columns[1]:
    render_card(
        "Total Objects Counted",
        total_counted,
        "Unique line crossings",
    )

with metric_columns[2]:
    render_card(
        "Left Crossings",
        left_count,
        "Right-to-left movement",
    )

with metric_columns[3]:
    render_card(
        "Right Crossings",
        right_count,
        "Left-to-right movement",
    )


# ============================================================
# CURRENT STATUS
# ============================================================

st.subheader("Current Object Status")

status_columns = st.columns(2)

with status_columns[0]:

    density_display = density.upper()

    if density_display == "LOW":
        density_description = "Low number of visible objects"
    elif density_display == "MODERATE":
        density_description = "Moderate number of visible objects"
    elif density_display == "HIGH":
        density_description = "High number of visible objects"
    else:
        density_description = "Current object density"

    render_card(
        "Object Density",
        density_display,
        density_description,
    )


with status_columns[1]:

    render_card(
        "Flow Rate",
        f"{flow_rate:.2f} objects/min",
        "Based on counted line crossings",
    )


# ============================================================
# OBJECT COMPOSITION
# ============================================================

st.subheader("Current Object Composition")

composition = pd.DataFrame(
    {
        "Object Type": [
            "Persons",
            "Bicycles",
            "Cars",
            "Motorcycles",
            "Buses",
            "Trucks",
            "Other Objects",
        ],
        "Count": [
            persons,
            bicycles,
            cars,
            motorcycles,
            buses,
            trucks,
            other_objects,
        ],
    }
)

composition = composition[
    composition["Count"] > 0
].reset_index(drop=True)


if not composition.empty:

    chart_columns = st.columns([1, 1])

    with chart_columns[0]:

        st.dataframe(
            composition,
            width="stretch",
            hide_index=True,
        )

    with chart_columns[1]:

        st.bar_chart(
            composition.set_index("Object Type")
        )

else:

    st.info(
        "No object classes are available in the latest logged frame."
    )


# ============================================================
# OBJECT TYPES DETECTED IN LATEST LOGGED FRAME
# ============================================================

object_type_data = parse_object_types(
    latest.get("object_types")
)


if object_type_data:

    st.subheader(
        "Detected Object Types in Latest Logged Frame"
    )

    object_type_df = pd.DataFrame(
        list(object_type_data.items()),
        columns=[
            "Object Type",
            "Count",
        ],
    )

    object_type_df = object_type_df.sort_values(
        "Count",
        ascending=False,
    ).reset_index(drop=True)

    st.dataframe(
        object_type_df,
        width="stretch",
        hide_index=True,
    )


# ============================================================
# TRACKED VIDEO
# ============================================================

st.subheader("Tracked Video")

video_path = None

if os.path.exists(selected_h264_output):
    video_path = selected_h264_output
elif os.path.exists(selected_raw_output):
    video_path = selected_raw_output
elif os.path.exists(selected_input_video):
    # Show the original input until analysis has been run.
    video_path = selected_input_video

if video_path:
    if video_path == selected_input_video:
        st.info(
            "This is the original input video. Click **Run Analysis** "
            "to generate the tracked result."
        )

    st.caption(f"Showing: {video_path}")

    try:
        with open(video_path, "rb") as video_file:
            video_bytes = video_file.read()

        st.video(
            video_bytes,
            format="video/mp4",
        )

    except Exception as exc:
        st.error(f"Could not load video: {exc}")
else:
    st.warning("No video found.")


# ============================================================
# TRAFFIC / OBJECT ANALYTICS
# ============================================================

st.subheader("Object Analytics")

analytics_df = df.copy()


if "frame" in analytics_df.columns:

    analytics_df = analytics_df.sort_values(
        "frame"
    )


# ------------------------------------------------------------
# Objects over time
# ------------------------------------------------------------

if "objects" in analytics_df.columns:

    st.markdown("#### Objects Visible Over Time")

    chart_data = analytics_df[
        ["frame", "objects"]
    ].copy()

    chart_data = chart_data.set_index(
        "frame"
    )

    st.line_chart(
        chart_data
    )

elif "vehicles" in analytics_df.columns:

    st.markdown("#### Objects Visible Over Time")

    chart_data = analytics_df[
        ["frame", "vehicles"]
    ].copy()

    chart_data = chart_data.rename(
        columns={
            "vehicles": "objects"
        }
    )

    chart_data = chart_data.set_index(
        "frame"
    )

    st.line_chart(
        chart_data
    )


# ------------------------------------------------------------
# Cumulative crossings
# ------------------------------------------------------------

if (
    "left_direction" in analytics_df.columns
    and "right_direction" in analytics_df.columns
):

    st.markdown("#### Cumulative Line Crossings")

    crossing_chart = analytics_df[
        [
            "frame",
            "left_direction",
            "right_direction",
        ]
    ].copy()

    crossing_chart = crossing_chart.set_index(
        "frame"
    )

    crossing_chart = crossing_chart.rename(
        columns={
            "left_direction": "Left",
            "right_direction": "Right",
        }
    )

    st.line_chart(
        crossing_chart
    )


# ============================================================
# DIRECTION ANALYSIS
# ============================================================

st.subheader("Direction Analysis")

direction_columns = st.columns(2)

with direction_columns[0]:

    render_card(
        "Left Crossings",
        left_count,
        "Objects moving right → left",
    )

with direction_columns[1]:

    render_card(
        "Right Crossings",
        right_count,
        "Objects moving left → right",
    )


# ============================================================
# COUNT VALIDATION
# ============================================================

st.subheader("Count Validation")

if os.path.exists(COUNT_REPORT_FILE):

    try:

        validation_df = pd.read_csv(
            COUNT_REPORT_FILE
        )

        if not validation_df.empty:

            latest_validation = (
                validation_df.iloc[-1]
            )

            manual_total = integer_value(
                latest_validation,
                "manual_total",
                0,
            )

            system_total = integer_value(
                latest_validation,
                "system_total",
                total_counted,
            )

            difference = integer_value(
                latest_validation,
                "difference",
                abs(
                    manual_total
                    - system_total
                ),
            )

            accuracy = number_value(
                latest_validation,
                "accuracy_percent",
                0,
            )

            validation_columns = st.columns(4)

            with validation_columns[0]:

                render_card(
                    "Manual Count",
                    manual_total,
                    "Human-verified count",
                )

            with validation_columns[1]:

                render_card(
                    "System Count",
                    system_total,
                    "SMARTFLOW count",
                )

            with validation_columns[2]:

                render_card(
                    "Difference",
                    difference,
                    "Manual vs system",
                )

            with validation_columns[3]:

                render_card(
                    "Accuracy",
                    f"{accuracy:.2f}%",
                    "Validation accuracy",
                )


            st.dataframe(
                validation_df,
                width="stretch",
                hide_index=True,
            )

        else:

            st.info(
                "Count validation file is empty."
            )

    except Exception as exc:

        st.error(
            f"Could not read count_report.csv: {exc}"
        )

else:

    st.info(
        "Count validation has not been created yet."
    )

    st.markdown(
        """
        The assignment requires a manual count comparison
        using the same video. After manual verification,
        update `reports/count_report.csv`.
        """
    )


# ============================================================
# COUNTING METHOD
# ============================================================

st.subheader("How SMARTFLOW Counts Objects")

st.markdown(
    """
    <div class="info-box">

    <b>1. Detection:</b>
    YOLO11 detects objects in every video frame.

    <br><br>

    <b>2. Tracking:</b>
    ByteTrack assigns a tracking ID to each detected object
    and attempts to maintain that ID across consecutive frames.

    <br><br>

    <b>3. Line Crossing:</b>
    SMARTFLOW calculates the center point of each tracked
    bounding box and checks whether it crosses the virtual
    counting line.

    <br><br>

    <b>4. Double-Count Prevention:</b>
    Once an object ID crosses the line, that ID is added to
    the counted-ID set. The same ID is not counted again.

    <br><br>

    <b>5. Object Classes:</b>
    The system is not restricted to vehicles. It can process
    persons, bicycles, cars, motorcycles, buses, trucks, and
    other classes supported by the YOLO model.

    </div>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# RAW DATA
# ============================================================

with st.expander("View Raw Traffic Data"):

    st.dataframe(
        df,
        width="stretch",
        hide_index=True,
    )


# ============================================================
# PIPELINE
# ============================================================

st.subheader("SMARTFLOW Pipeline")

pipeline_columns = st.columns(5)

pipeline_steps = [
    ("1", "Video", "Selected input video"),
    ("2", "YOLO11", "Object detection"),
    ("3", "ByteTrack", "Object tracking"),
    ("4", "Line Crossing", "Unique counting"),
    ("5", "Dashboard", "Analytics & visualization"),
]

for column, step in zip(
    pipeline_columns,
    pipeline_steps,
):

    number, title, description = step

    with column:

        st.markdown(
            f"""
            <div class="status-card">
                <div class="status-label">Step {number}</div>
                <div class="status-value">{title}</div>
                <div class="status-description">
                    {description}
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )


# ============================================================
# TECHNOLOGY STACK
# ============================================================

st.subheader("Technology Stack")

technology_df = pd.DataFrame(
    {
        "Component": [
            "Object Detection",
            "Object Tracking",
            "Video Processing",
            "Dashboard",
            "Data Storage",
        ],
        "Technology": [
            "YOLO11",
            "ByteTrack",
            "OpenCV",
            "Streamlit",
            "CSV / Pandas",
        ],
    }
)

st.dataframe(
    technology_df,
    width="stretch",
    hide_index=True,
)


# ============================================================
# PROJECT OBJECTIVE
# ============================================================

st.subheader("Project Objective")

st.write(
    """
    SMARTFLOW is a computer vision system for detecting,
    tracking, and counting moving objects in video without
    double-counting. The system combines YOLO11 object
    detection with ByteTrack multi-object tracking and a
    virtual line-crossing method. Each tracked object receives
    an ID, and a counted-ID set prevents the same tracked
    object from being counted multiple times.
    """
)



